# Generated by Django 2.2 on 2019-12-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Clave')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('link', models.URLField(verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
